version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./CurrencyXchange/prometheus:/etc/prometheus
    command: 
     - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
    volumes:
      - ./CurrencyXchange/grafana:/var/lib/grafana
      - ./CurrencyXchange/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./CurrencyXchange/grafana/datasources:/etc/grafana/provisioning/datasources
    
  
  
  backend:
    build: ./CurrencyXchange
    image: currencyxchange-api
    networks:
      - my-network
    ports:
      - "8080:8080"
    
    
  frontend:
    build: ./currencyXchange-ui
    image: currencyxchange-ui
    ports:
      - "4200:4200"
    networks:
      - my-network
networks:
  my-network:
    name: my-network
