apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: true
    basicAuth: true
    editable: true
    uid: DS_PROMETHEUS
    