package com.currency.exchange.model;

import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonInclude;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Represents a response object for currency exchange operations.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CurrencyResponse {

	/**
	 * The currency code to convert from.
	 */
	private String fromCurrency;

	/**
	 * The currency code to convert to.
	 */
	private String toCurrency;

	/**
	 * The amount of currency to exchange.
	 */
	private BigDecimal amount;

	/**
	 * The converted amount after currency exchange.
	 */
	private BigDecimal convertedAmount;

	/**
	 * Error message in case of any validation or processing error.
	 */
	private String errorMessage;

	// Constructors, getters, setters, and Builder pattern are generated by Lombok
	// annotations
}
