package com.currency.exchange.model;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Represents an exchange rate between two currencies.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
public class Rate {

	/**
	 * The exchange rate amount.
	 */
	private BigDecimal amount;
	
	/**
	 * The currency code to convert from.
	 */
	private String fromCurrency;

	/**
	 * The currency code to convert to.
	 */
	private String toCurrency;
	
	// Constructors, getters, setters, and toString method are generated by Lombok annotations

}