global:
  scrape_interval:     2s # How frequently to scrape targets by default.

scrape_configs:
  - job_name: 'currencyxchange'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Assuming your Spring Boot app is running on localhost:5000
